const education = [
  {
    title: 'MS in Computer Science and Engineering',
    organization: 'University of Washington',
    startDate: 'sep 2024',
    endDate: 'present',
    skills: [
      'computer graphics',
      'virtual reality systems',
      'game development',
      'computational design and fabrication',
      'data visualization',
      'machine learning systems',
      'quantum computation',
      'digital design',
      'random algorithms',
    ],
  },
  {
    title: 'BS in Computer Science',
    organization: 'University of Washington',
    startDate: 'sep 2020',
    endDate: 'jun 2024',
    skills: [
      'compilers',
      'operating systems',
      'distributed systems',
      'web browser engineering',
      'programming languages',
      'database internals',
      'data center systems',
      'computer security',
      'computer networks',
      'artificial intelligence',
      'machine learning',
      'deep learning',
      'natural language processing',
      'computer vision',
      'autonomous robotics',
      'algorithms',
      'complexity',
    ],
  },
  {
    title: 'BA in Mathematics',
    organization: 'University of Washington',
    startDate: 'sep 2020',
    endDate: 'jun 2024',
    skills: [
      'probability',
      'advanced linear algebra',
      'real analysis',
      'complex analysis',
      'ring theory',
      'group theory',
      'field theory',
      'combinatorial theory',
      'linear optimization',
      'topology',
      'differential geometry',
    ],
  },
]

export default education
